### ISSUE TITLE
Allow parameters in command definitions in runner.yml

### ISSUE THREAD

**Issue by donquixote** [openeuropa/task-runner#111]
In #25 the option was added to define commands inside the runner.yml(.dist) file.

It would be nice if we could also add parameters to those commands.

Currently this has to be defined like so, by specifying the full cli command as a single string:

```yml
commands:
  efd:build-themes:
  - "${runner.bin_dir}/run efd:npm-build --npm-dir=path/to/npm/root"
```

With support for parameters / arguments, it could look like this:

```yml
commands:
  efd:build-themes:
  -
    task: "run"
    command: "efd:npm-build"
    arguments: {npm-dir: "path/to/npm/root"}
```

(The example is inspired from this, https://github.com/ec-europa/ecdc-vaccine-reference/blob/6cf99aec072e0b6616cc6a0967be692692c53103/src/TaskRunner/Commands/EcdcBuildCommands.php#L71)
