### ISSUE TITLE
Add an 'exec' task for dynamic commands. Deprecate usage of plain strings

### ISSUE THREAD

**Issue by claudiu-cristea** [openeuropa/task-runner#123]
## Problem

Right now, you can add a command line in a dynamic command list:

```yaml
...
commands:
  some-comamnd:
    - ...
    - echo -n "Hello World!"
```

However, this creates issues with TTY in PHPUnit tests. Also, it's not consistent with the rest of the tasks.

## Proposal

Add a new `exec` task to handle such cases. The abob dynamic command definition would look:

```yaml
...
commands:
  some-comamnd:
    - ...
    - { task: "exec", command: "echo", arguments: ["Hello World!"], options: { "-n": null } }
```
or
```yaml
...
commands:
  some-comamnd:
    - ...
    - task: exec
      command: echo
      arguments:
        - Hello World!
      options:
        '-n': null
```

Deprecate usage of task as plain string.
